name: Update README

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Update README
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          user: mrayanasim09  # Replace with your GitHub username
          template: classic

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update README [skip ci]"
          git push
